<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-13 at 21:07:47.
 */
require \dirname(__FILE__).'\..\..\modelo\Disciplina.php';
class DisciplinaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Disciplina
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Disciplina('DCE', '1234', 'gestao', '3', '2013',
                '234151', 'A', '20', 'matutino','8:00','2', 'discilina de gestao',
                '1111');
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
            $this->object = null;
    }

    /**
     * @covers Disciplina::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
       $this->object->set('codigo', '1234');
       $this->assertEquals('1234', $this->object->get('codigo'));
    }

    /**
     * @covers Disciplina::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
       $this->object->set('codigo', '1234');
       $this->assertEquals('1234', $this->object->get('codigo'));
    }

}
