<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-13 at 21:15:24.
 */
require \dirname(__FILE__).'\..\..\modelo\Professor.php';

class ProfessorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Professor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Professor('0001', '0001', '0002', 'joao teste','teste@email.com', '11111111' );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
      $this->object = null;   
    }
    
    /**
     * @covers Professor::__construct
     * @todo   Implement test__construct().
     */
    protected function testConstruct(){
        $this->assertEquals('0001',$this->object->get('idProfessor'));
        $this->assertEquals('0001',$this->object->get('idUsuario'));
        $this->assertEquals('0002',$this->object->get('idSecretaria'));
        $this->assertEquals('joao teste',$this->object->get('professor_nome'));
        $this->assertEquals('teste@email.com',$this->object->get('professor_email'));
        $this->assertEquals('11111111',$this->object->get('professor_contatoTelefone'));
    }

    /**
     * @covers Professor::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->object->set('professor_nome', 'rodrigo');
       $this->assertEquals('rodrigo', $this->object->get('professor_nome'));
    }

    /**
     * @covers Professor::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
         $this->object->set('professor_nome', 'rodrigo');
       $this->assertEquals('rodrigo', $this->object->get('professor_nome'));
    }

}
