<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-13 at 20:46:32.
 */
require \dirname(__FILE__) . '\..\..\modelo\Secretaria.php';

class SecretariaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Secretaria
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Secretaria('rua');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        $this->object = null;
    }

    /**
     * @covers Candidato::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->object->set('enderecoLogo', 'rua');
        $this->assertEquals('rua', $this->object->get('enderecoLogo'));
    }

    /**
     * @covers Candidato::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $this->object->set('enderecoLogo', 'rua');
        $this->assertEquals('rua', $this->object->get('enderecoLogo'));
    }

}
