<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-13 at 21:20:39.
 */
require \dirname(__FILE__).'\..\..\modelo\Usuario.php';

class UsuarioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Usuario
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Usuario('1', 'rodrigo', '123456', '1');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
         $this->object = null;
    }

    /**
     * @covers Usuario::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->object->set('senha', '000000');
        $this->assertEquals('000000', $this->object->get('senha'));
    }

    /**
     * @covers Usuario::get
     * @todo   Implement testGet().
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
         $this->assertEquals('123456', $this->object->get('senha'));
    }

}
