<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-14 at 22:45:23.
 */
require_once \dirname(__FILE__) . '\..\..\DAO\CandidatoDAO.php';

require_once \dirname(__FILE__) .'\..\..\controle\ConexaoBanco.php';

require_once \dirname(__FILE__) . '\..\..\modelo\Candidato.php';



class CandidatoDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CandidatoDAO
     */
    protected $candidato;
    
    /* @var $conexao  */
    private $conexao;
    
    /* @var $idCandidato  */
    protected $idCandidato;
    
    /* @var $idCandidato  */
    protected $candidatoDao;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        /*
        $cpf ='03592079107';
        $email = 'ramaiane@gmail.com';
        $telefone = '12345678';
        $nome = 'ramaiane';
        $instituicaoGraduacao = 'unb';
        $cursoGraduacao = 'engenharia';
        $dataAdmissaoGraduacao = '12-12-2009';
        $dataConclusaoGraduacao = '12-12-2014';
        */
        $this->candidato = new Candidato();
        $this->candidatoDao = new CandidatoDAO;
        
        $this->getConnection();
        
       
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       /* $sql = "DELETE FROM candidato WHERE nome = 'ramaiane';";
        $this->db->exec($sql);
        $sql = "DELETE FROM candidato WHERE cpf = '03592079107';";
        $this->db->exec($sql);*/
        
     $this->idCandidato = mysql_insert_id();
    /* $candidatoDao = new CandidatoDAO();
     $res = $candidatoDao->excluiCandidato($this->idCandidato-1);
     echo 'SAIDA-->'.res;*/
    }
    
    public function getConnection(){
       
        $this->conexao = new ConexaoBanco;
        
        return $this->conexao->conectar();
    }

    /**
     * @covers CandidatoDAO::resetaConexao
     * @todo   Implement testResetaConexao().
     */
    public function testResetaConexao() {
        $this->assertNull($this->candidatoDao->resetaConexao());
        
    }

    /**
     * @covers CandidatoDAO::insereCandidato
     * @todo   Implement testInsereCandidato().
     */
    public function testInsereCandidato() {
        $candidatoDao = new CandidatoDAO();
        
        $this->idCandidato = $candidatoDao->insereCandidato($this->candidato);
        $this->assertNull($this->idCandidato);
        
        //$this->object->insereCandidato();
        //$this->assertEquals('03592079107', $obj->cpf);
      
    }

    /**
     * @covers CandidatoDAO::atualizaCandidatoDados
     * @todo   Implement testAtualizaCandidatoDados().
     */
   /* public function testAtualizaCandidatoDados() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CandidatoDAO::atualizaLogin
     * @todo   Implement testAtualizaLogin().
     */
  /*  public function testAtualizaLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CandidatoDAO::recuperaDadosCandidato
     * @todo   Implement testRecuperaDadosCandidato().
     */
   /* public function testRecuperaDadosCandidato() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CandidatoDAO::excluiCandidato
     * @todo   Implement testExcluiCandidato().
     */
   /* public function testExcluiCandidato() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CandidatoDAO::defineNovoCandidato
     * @todo   Implement testDefineNovoCandidato().
     */
  /*  public function testDefineNovoCandidato() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
*/
}
