<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-16 at 08:09:20.
 */
require_once \dirname(__FILE__) . '\..\..\DAO\ProfessorDAO.php';

require_once \dirname(__FILE__) . '\..\..\controle\ConexaoBanco.php';

require_once \dirname(__FILE__) . '\..\..\modelo\Professor.php';

class ProfessorDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ProfessorDAO
     */
    protected $professorDao;

    protected $conexao;
    
    protected $professor;

    protected $idProfessor;



    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->professorDao = new ProfessorDAO;
        
        $this->professor = new Professor;
        
        $this->getConnection();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
       
        
    }

     public function getConnection(){
       
        $this->conexao = new ConexaoBanco;
        $conect = $this->conexao->conectar();
        return $conect;
    }
    /**
     * @covers ProfessorDAO::insereProfessor
     * @todo   Implement testInsereProfessor().
     */
    public function testInsereProfessor() {
        $this->professor->set('professor_nome', 'teste');
        $this->professor->set('professor_email', 'email@teste.com');
        $this->professor->set('professor_contatoTelefone', '12345678');
        $this->professor->set('tipo', 3);
        $this->professorDao = new ProfessorDAO();
        
        $this->idProfessor = null;
        $this->assertNull($this->idProfessor);
    }

    /**
     * @covers ProfessorDAO::atualizaDadosProfessor
     * @todo   Implement testAtualizaDadosProfessor().
     */
   /* public function testAtualizaDadosProfessor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfessorDAO::atualizaLogin
     * @todo   Implement testAtualizaLogin().
     */
   /* public function testAtualizaLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfessorDAO::recuperaDadosProfessor
     * @todo   Implement testRecuperaDadosProfessor().
     */
   /* public function testRecuperaDadosProfessor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfessorDAO::excluiProfessor
     * @todo   Implement testExcluiProfessor().
     */
   /* public function testExcluiProfessor() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }*/

}
