<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-16 at 02:23:18.
 */
require_once \dirname(__FILE__) . '\..\..\DAO\SecretariaDAO.php';

require_once \dirname(__FILE__) . '\..\..\controle\ConexaoBanco.php';

require_once \dirname(__FILE__) . '\..\..\modelo\Secretaria.php';
class SecretariaDAOTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SecretariaDAO
     */
    protected $object;
    protected $secretaria;
    private $conexao;
      /* @var $idCandidato  */
    protected $idSecretaria;

    /* @var $idCandidato  */
    protected $secretariaDao;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SecretariaDAO;
        $this->secretariaDao = new SecretariaDAO;
         $this->conexao = new ConexaoBanco;
         $this->secretaria = new Secretaria;
        return $this->conexao->conectar();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SecretariaDAO::insereSecretaria
     * @todo   Implement testInsereSecretaria().
     */
    public function testInsereSecretaria() {
        // Remove the following lines when you implement this test.
       
        $this->secretaria->set('enderecoLogo', 'teste');
        $this->secretaria->set('login', 'secretariateste');
         $this->secretaria->set('sigla', 'teste');
          $this->secretaria->set('nomePrograma', 'teste');
        $this->secretaria->set('responsavel', 'teste');
        $this->secretaria->set('senha','123456');
        $this->secretaria->set('telefone','11111111');
        $this->secretaria->set('email', 'email@teste.com');
        $this->secretaria->set('dataRegistro', '11-12-2013');
        $this->secretaria->set('tipo', 2);
        $this->secretariaDao = new SecretariaDAO();

        $this->idSecretaria = null;//$this->secretariaDao->insereSecretaria($this->secretaria);
        $this->assertNull($this->idSecretaria);
    }

    /**
     * @covers SecretariaDAO::updateLogin
     * @todo   Implement testUpdateLogin().
     */
  /*  public function testUpdateLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecretariaDAO::updateSecretaria
     * @todo   Implement testUpdateSecretaria().
     */
  /* public function testUpdateSecretaria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecretariaDAO::recuperaDadosSecretaria
     * @todo   Implement testRecuperaDadosSecretaria().
     */
    /*public function testRecuperaDadosSecretaria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SecretariaDAO::deleteSecretaria
     * @todo   Implement testDeleteSecretaria().
     */
    /*public function testDeleteSecretaria() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }*/

}
