<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-13 at 21:35:37.
 */
require \dirname(__FILE__) . '\..\..\controle\ValidaDados.php';

class ValidaDadosTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ValidaDados
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidaDados;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ValidaDados::checaCampoEmBranco
     * @todo   Implement testChecaCampoEmBranco().
     */
    public function testChecaCampoEmBranco() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->checaCampoEmBranco('teste'));
    }

    /**
     * @covers ValidaDados::validaEmail
     * @todo   Implement testValidaEmail().
     */
    public function testValidaEmail() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->validaEmail('teste@email.com'));
    }

    /**
     * @covers ValidaDados::verificaCPF
     * @todo   Implement testVerificaCPF().
     */
    public function testVerificaCPF() {
        $this->assertTrue($this->object->verificaCPF('11111111111'));
    }

    /**
     * @covers ValidaDados::verificaSenha
     * @todo   Implement testVerificaSenha().
     */
    public function testVerificaSenha() {
        $this->assertTrue($this->object->verificaSenha('123456','123456'));
    }

    /**
     * @covers ValidaDados::campoNumerico
     * @todo   Implement testCampoNumerico().
     */
    public function testCampoNumerico() {
        $this->assertTrue($this->object->campoNumerico('11111111'));
    }

}
