<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-14 at 18:51:57.
 */
require \dirname(__FILE__) . '\..\..\controle\ValidaDadosCandidato.php';

class ValidaDadosCandidatoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ValidaDadosCandidato
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidaDadosCandidato;
    
        $this->object->set('login', 'teste');
        $this->object->set('nomeCompleto', 'rodrigo teste');
        $this->object->set('senha1', '123456');
        $this->object->set('senha2', '123456');
        $this->object->set('cpf', '11111111111');
        $this->object->set('email', 'teste@email.com');    
        $this->object->set('telefone', '11111111');
        $this->object->set('conclusao', 'teste');

        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ValidaDadosCandidato::set
     * @todo   Implement testSet().
     */
    public function testSet() {
        // Remove the following lines when you implement this test.
        $this->object->set('cpf', '11111111111');
        $this->assertEquals('11111111111',  $this->object->get('cpf'));
    }
     public function testGet() {
        // Remove the following lines when you implement this test.
        $this->object->set('cpf', '11111111111');
        $this->assertEquals('11111111111',  $this->object->get('cpf'));
    }
    /**
     * @covers ValidaDadosCandidato::validarGeral
     * @todo   Implement testValidarGeral().
     */
    public function testValidarGeral() {
        // Remove the following lines when you implement this test.
        $this->assertNull($this->object->validarGeral());
    }

    /**
     * @covers ValidaDadosCandidato::checaCampos
     * @todo   Implement testChecaCampos().
     */
    public function testChecaCampos() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->checaCampos());
    }

    /**
     * @covers ValidaDadosCandidato::verificaEmail
     * @todo   Implement testVerificaEmail().
     */
    public function testVerificaEmail() {
        $this->assertTrue($this->object->verificaEmail());
    }

    /**
     * @covers ValidaDadosCandidato::verificaCPF
     * @todo   Implement testVerificaCPF().
     */
    public function testVerificaCPF() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->verificaCPF());
    }

    /**
     * @covers ValidaDadosCandidato::verificaSenha
     * @todo   Implement testVerificaSenha().
     */
    public function testVerificaSenha() {
        $this->assertTrue($this->object->verificaSenha());
    }

}
