<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-14 at 20:33:41.
 */
require \dirname(__FILE__) . '\..\..\controle\ValidaDadosSecretaria.php';

class ValidaDadosSecretariaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ValidaDadosSecretaria
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidaDadosSecretaria;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ValidaDadosSecretaria::checaCampoEmBranco
     * @todo   Implement testChecaCampoEmBranco().
     */
    public function testChecaCampoEmBranco() {
        // Remove the following lines when you implement this test.
        $this->assertTrue($this->object->checaCampoEmBranco('teste'));
    }

    /**
     * @covers ValidaDadosSecretaria::validaEmail
     * @todo   Implement testValidaEmail().
     */
    public function testValidaEmail() {
        // Remove the following lines when you implement this test.
         $this->assertTrue($this->object->validaEmail('teste@email.com'));
    }

    /**
     * @covers ValidaDadosSecretaria::verificaSenha
     * @todo   Implement testVerificaSenha().
     */
    public function testVerificaSenha() {
        // Remove the following lines when you implement this test.
         $this->assertTrue($this->object->verificaSenha('123456','123456'));
    }

    /**
     * @covers ValidaDadosSecretaria::campoNumerico
     * @todo   Implement testCampoNumerico().
     */
    public function testCampoNumerico() {
        // Remove the following lines when you implement this test.
         $this->assertTrue($this->object->campoNumerico('11111111'));
    }

}
